---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: ewatkins-dev-production-tls
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - kind: ClusterSecretStore
      name: bitwarden-secrets-manager
  selector:
    secret:
      name: ewatkins-dev-production-tls
  template:
    engineVersion: v2
    data:
      cert: |
        {
          "tls_crt": "{{ index . "tls.crt" | b64enc }}",
          "tls_key": "{{ index . "tls.key" | b64enc }}"
        }

  data:
    - match:
        secretKey: cert
        remoteRef:
          remoteKey: ewatkins-dev-production-tls
          property: cert
