apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: auraskills
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: auraskills
  table: "*"
  username: auraskills
