apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: bluemap
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: bluemap
  table: "*"
  username: bluemap
