apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: essentialsxgui
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: essentialsxgui
  table: "*"
  username: essentialsxgui
