apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: luckperms
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: luckperms
  table: "*"
  username: luckperms
