apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: playerpoints
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: playerpoints
  table: "*"
  username: playerpoints
