apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: ultraspawners
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: ultraspawners
  table: "*"
  username: ultraspawners
