apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: wildstacker
spec:
  mariaDbRef:
    name: mariadb
  privileges:
    - "ALL PRIVILEGES"
  database: wildstacker
  table: "*"
  username: wildstacker
