---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./authentik.yaml
  - ./cilium.yaml
  - ./cloudnative-pg.yaml
  - ./external-dns.yaml
  - ./fairwinds.yaml
  - ./grafana.yaml
  - ./ingress-nginx.yaml
  - ./k8s-gateway.yaml
  - ./jetstack.yaml
  - ./metrics-server.yaml
  - ./node-feature-discovery.yaml
  - ./openebs.yaml
  - ./postfinance.yaml
  - ./runix.yaml
  - ./stakater.yaml
