---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./actions-runner-controller.yaml
  - ./app-template.yaml
  - ./bjw-s.yaml
  - ./envoy-gateway.yaml
  - ./crunchy-users.yaml
  - ./forgejo.yaml
  - ./prometheus-community.yaml
  - ./spegel.yaml
  - ./stevehipwell.yaml
