---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: authentik
  namespace: security
spec:
  endpoints:
    - dnsName: auth.ewatkins.dev
      recordTTL: 1
      recordType: CNAME
      targets:
        - "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
