---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: mariadb
        group: infrastructure
        url: tcp://10.40.0.120:3306
        interval: 1m
        conditions: ["[CONNECTED] == true"]
        ui:
          hide-url: true
          hide-hostname: true
