---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: maxscale
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.ewatkins.dev
spec:
  ingressClassName: internal
  tls:
    - hosts:
        - &host maxscale.ewatkins.dev
  rules:
    - host: *host
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: maxscale-gui
                port:
                  number: 8989
