apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mariadb-cluster
  namespace: flux-system
resources:
  - ./externalsecret.yaml
  - ./mariadb.yaml
  - ./maxscale.yaml
  - ./ingress.yaml

  # Pterodactyl
  - ./users/pterodactyl.yaml
  - ./grants/pterodactyl.yaml

  # LuckPerms
  - ./users/luckperms.yaml
  - ./databases/luckperms.yaml
  - ./grants/luckperms.yaml
  - ./connections/luckperms.yaml
