apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: mariadb-cluster
  namespace: flux-system
resources:
  - ./externalsecret.yaml
  - ./mariadb.yaml
  - ./maxscale.yaml
  - ./ingress.yaml

  # Pterodactyl
  - ./users/pterodactyl.yaml
  - ./grants/pterodactyl.yaml

  # LuckPerms
  - ./users/luckperms.yaml
  - ./databases/luckperms.yaml
  - ./grants/luckperms.yaml

  # Bluemap
  - ./users/bluemap.yaml
  - ./databases/bluemap.yaml
  - ./grants/bluemap.yaml

  # Jobs
  - ./users/jobs.yaml
  - ./databases/jobs.yaml
  - ./grants/jobs.yaml

  # PlayerPoints
  - ./users/playerpoints.yaml
  - ./databases/playerpoints.yaml
  - ./grants/playerpoints.yaml

  # EssentialsX GUI
  - ./users/essentialsxgui.yaml
  - ./databases/essentialsxgui.yaml
  - ./grants/essentialsxgui.yaml

  # AuraSkills
  - ./users/auraskills.yaml
  - ./databases/auraskills.yaml
  - ./grants/auraskills.yaml

  # UltraSpawners
  - ./users/ultraspawners.yaml
  - ./databases/ultraspawners.yaml
  - ./grants/ultraspawners.yaml

  # Privault
  - ./users/privault.yaml
  - ./databases/privault.yaml
  - ./grants/privault.yaml
