apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: helmrelease.mariadb-operator-crds
  namespace: flux-system
resources:
  - ./externalsecret.yaml
  - ./mariadb.yaml

  # Pterodactyl
  - ./users/pterodactyl.yaml
  - ./grants/pterodactyl.yaml

  # LuckPerms
  - ./users/luckperms.yaml
  - ./databases/luckperms.yaml
  - ./grants/luckperms.yaml
