apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-root-secret
    key: password

  storage:
    size: 5Gi
    storageClassName: openebs-hostpath

  replicas: 3

  galera:
    enabled: true
    recovery:
      podSyncTimeout: 30m0s
      clusterBootstrapTimeout: 40m0s

  startupProbe:
    failureThreshold: 360

  metrics:
    enabled: true

  service:
    type: LoadBalancer
    metadata:
      annotations:
        lbipam.cilium.io/ips: ${MARIADB}

  myCnf: |
    [mariadb]
    transaction_isolation = READ-COMMITTED
