apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: mariadb
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-root-secret
    key: password

  storage:
    size: 5Gi
    storageClassName: openebs-hostpath

  replicas: 3

  galera:
    enabled: true

  metrics:
    enabled: true

  myCnf: |
    [mariadb]
    transaction_isolation = READ-COMMITTED
