---
clusterName: great-lakes
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.12.4
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.35.0
endpoint: https://10.40.1.100:6443
allowSchedulingOnControlPlanes: true
cniConfig:
  name: none
additionalApiServerCertSans:
  - cluster.local
clusterPodNets:
  - 10.69.0.0/16
clusterSvcNets:
  - 10.96.0.0/16
patches:
  - |-
    machine:
      kubelet:
        nodeIP:
          validSubnets:
            - 10.40.0.1/16
        extraMounts:
          - destination: /var/openebs/local
            type: bind
            source: /var/openebs/local
            options:
              - rbind
              - rshared
              - rw
        extraArgs:
          rotate-server-certificates: "true"
nodes:
  - hostname: superior
    ipAddress: 10.40.1.1
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:77:01
        dhcp: true
        vip:
          ip: 10.40.1.100
  - hostname: huron
    ipAddress: 10.40.1.2
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:77:02
        dhcp: true
        vip:
          ip: 10.40.1.100
  - hostname: michigan
    ipAddress: 10.40.1.3
    controlPlane: true
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:77:03
        dhcp: true
        vip:
          ip: 10.40.1.100
  - hostname: erie
    ipAddress: 10.40.1.4
    controlPlane: false
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:77:04
        dhcp: true
  - hostname: ontario
    ipAddress: 10.40.1.5
    controlPlane: false
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:77:05
        dhcp: true
controlPlane:
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/i915
          - siderolabs/qemu-guest-agent
  nameservers:
    - 10.0.0.1
  certSANs:
    # Node IPs
    - 10.40.1.1
    - 10.40.1.2
    - 10.40.1.3
    # Load balancers / VIPs
    - 10.40.1.100
    # Pod/Service Networks
    - 10.69.0.0/16
    - 10.96.0.0/16
  machineFiles:
    - content: |-
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
          device_ownership_from_security_context = true
      permissions: 0
      path: /etc/cri/conf.d/20-customization.part
      op: create
  disableSearchDomain: true
  patches:
    - |-
      cluster:
        apiServer:
          extraArgs:
            feature-gates: MutatingAdmissionPolicy=true
            runtime-config: admissionregistration.k8s.io/v1beta1=true
        controllerManager:
          extraArgs:
            bind-address: "0.0.0.0"
        scheduler:
          extraArgs:
            bind-address: "0.0.0.0"
        etcd:
          extraArgs:
            listen-metrics-urls: "http://0.0.0.0:2381"
    - |-
      machine:
        sysctls:
          fs.inotify.max_queued_events: "65536"
          fs.inotify.max_user_instances: "8192"
          fs.inotify.max_user_watches: "524288"
          net.core.rmem_max: "2500000"
          net.core.wmem_max: "2500000"
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
                - os:admin
            allowedKubernetesNamespaces:
                - actions-runner-system
                - system-upgrade
          kubePrism:
            enabled: true
            port: 7445
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
worker:
  nameservers:
    - 10.0.0.1
  certSANs:
    # Node IPs
    - 10.40.1.4
    - 10.40.1.5
    # Pod/Service Networks
    - 10.69.0.0/16
    - 10.96.0.0/16
  machineFiles:
    - content: |-
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
          device_ownership_from_security_context = true
      permissions: 0
      path: /etc/cri/conf.d/20-customization.part
      op: create
  disableSearchDomain: true
  schematic:
    customization:
      extraKernelArgs:
        - net.ifnames=0
      systemExtensions:
        officialExtensions:
          - siderolabs/intel-ucode
          - siderolabs/i915
          - siderolabs/qemu-guest-agent
  patches:
    - |-
      machine:
        sysctls:
          fs.inotify.max_queued_events: "65536"
          fs.inotify.max_user_instances: "8192"
          fs.inotify.max_user_watches: "524288"
          net.core.rmem_max: "2500000"
          net.core.wmem_max: "2500000"
    - |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
