---
clusterName: great-lakes
talosVersion: v1.12.0
kubernetesVersion: v1.34.3
endpoint: https://10.30.4.0:6443
allowSchedulingOnControlPlanes: true
cniConfig:
  name: none
additionalApiServerCertSans:
  - cluster.local
clusterPodNets:
  - 10.69.0.0/16
clusterSvcNets:
  - 10.96.0.0/16
nodes:
  - hostname: superior
    controlPlane: true
    ipAddress: 10.30.4.1
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:76:01
        addresses:
          - 10.30.4.1/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 1500
        dhcp: false
        vip:
          ip: 10.30.4.0
  - hostname: huron
    controlPlane: true
    ipAddress: 10.30.4.2
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:76:02
        addresses:
          - 10.30.4.2/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 1500
        dhcp: false
        vip:
          ip: 10.30.4.0
  - hostname: michigan
    controlPlane: true
    ipAddress: 10.30.4.3
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:76:03
        addresses:
          - 10.30.4.3/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 1500
        dhcp: false
        vip:
          ip: 10.30.4.0
  - hostname: erie
    controlPlane: false
    ipAddress: 10.30.4.4
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:76:04
        addresses:
          - 10.30.4.4/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 1500
        dhcp: false
  - hostname: ontario
    controlPlane: false
    ipAddress: 10.30.4.5
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:76:05
        addresses:
          - 10.30.4.5/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 1500
        dhcp: false
controlPlane:
  nameservers:
    - 10.0.0.1
  certSANs:
    - 127.0.0.1
    - 10.30.4.0
  machineFiles:
    - content: |-
        [plugins."io.containerd.grpc.v1.cri"]
          enable_unprivileged_ports = true
          enable_unprivileged_icmp = true
        [plugins."io.containerd.grpc.v1.cri".containerd]
          discard_unpacked_layers = false
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          discard_unpacked_layers = false
      permissions: 0
      path: /etc/cri/conf.d/20-customization.part
      op: create
  disableSearchDomain: true
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/qemu-guest-agent
  patches:
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/openebs/local
              type: bind
              source: /var/openebs/local
              options:
                - rbind
                - rshared
                - rw
    - |-
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: "false"
    - |-
      machine:
        sysctls:
          fs.inotify.max_queued_events: "65536"
          fs.inotify.max_user_instances: "8192"
          fs.inotify.max_user_watches: "524288"
          net.core.rmem_max: "2500000"
          net.core.wmem_max: "2500000"
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
                - os:admin
            allowedKubernetesNamespaces:
                - actions-runner-system
                - system-upgrade
          kubePrism:
            enabled: true
            port: 7445
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
    - |
      machine:
        network:
          extraHostEntries:
            - ip: 10.30.4.1
              aliases:
                - superior
                - superior.ewatkins.dev
            - ip: 10.30.4.2
              aliases:
                - huron
                - huron.ewatkins.dev
            - ip: 10.30.4.3
              aliases:
                - michigan
                - michigan.ewatkins.dev
            - ip: 10.30.4.4
              aliases:
                - erie
                - erie.ewatkins.dev
            - ip: 10.30.4.5
              aliases:
                - ontario
                - ontario.ewatkins.dev
worker:
  nameservers:
    - 10.0.0.1
  certSANs:
    - 127.0.0.1
    - 10.30.4.0
  machineFiles:
    - content: |-
        [plugins."io.containerd.grpc.v1.cri"]
          enable_unprivileged_ports = true
          enable_unprivileged_icmp = true
        [plugins."io.containerd.grpc.v1.cri".containerd]
          discard_unpacked_layers = false
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
          discard_unpacked_layers = false
      permissions: 0
      path: /etc/cri/conf.d/20-customization.part
      op: create
  disableSearchDomain: true
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/qemu-guest-agent
  patches:
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/openebs/local
              type: bind
              source: /var/openebs/local
              options:
                - rbind
                - rshared
                - rw
    - |-
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: "false"
    - |-
      machine:
        sysctls:
          fs.inotify.max_queued_events: "65536"
          fs.inotify.max_user_instances: "8192"
          fs.inotify.max_user_watches: "524288"
          net.core.rmem_max: "2500000"
          net.core.wmem_max: "2500000"
    - |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
    - |
      machine:
        network:
          extraHostEntries:
            - ip: 10.30.4.1
              aliases:
                - superior
                - superior.ewatkins.dev
            - ip: 10.30.4.2
              aliases:
                - huron
                - huron.ewatkins.dev
            - ip: 10.30.4.3
              aliases:
                - michigan
                - michigan.ewatkins.dev
            - ip: 10.30.4.4
              aliases:
                - erie
                - erie.ewatkins.dev
            - ip: 10.30.4.5
              aliases:
                - ontario
                - ontario.ewatkins.dev
