---
clusterName: great-lakes
# renovate: datasource=docker depName=ghcr.io/siderolabs/installer
talosVersion: v1.12.0
# renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
kubernetesVersion: v1.35.0
endpoint: https://10.40.1.1:6443
allowSchedulingOnControlPlanes: true
cniConfig:
  name: none
additionalApiServerCertSans:
  - cluster.local
clusterPodNets:
  - 10.40.64.0/18
clusterSvcNets:
  - 10.40.128.0/17
nodes:
  - hostname: superior
    controlPlane: true
    ipAddress: 10.40.1.1
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:76:01
        addresses:
          - 10.30.4.1/11
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 1500
        dhcp: false
      - deviceSelector:
          hardwareAddr: bc:24:11:be:77:01
        addresses:
          - 10.40.1.1/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1
            metric: 100
        vip:
          ip: 10.40.1.0
    certSANs:
      # Node IPs (new network)
      - 10.40.1.1
      - 10.40.1.2
      - 10.40.1.3
      - 10.40.1.4
      - 10.40.1.5
      # Old node IPs (during migration)
      - 10.30.4.1
      - 10.30.4.2
      - 10.30.4.3
      - 10.30.4.4
      - 10.30.4.5
      # Load balancers / VIPs
      - 10.30.4.0
      - 10.40.1.0
      # DNS names
      - kubernetes
      - kubernetes.default
      - kubernetes.default.svc
      - kubernetes.default.svc.cluster.local
  - hostname: huron
    controlPlane: true
    ipAddress: 10.40.1.2
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:76:02
        addresses:
          - 10.30.4.2/11
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 1500
        dhcp: false
      - deviceSelector:
          hardwareAddr: bc:24:11:be:77:02
        addresses:
          - 10.40.1.2/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1
            metric: 100
        vip:
          ip: 10.40.1.0
    certSANs:
      # Node IPs (new network)
      - 10.40.1.1
      - 10.40.1.2
      - 10.40.1.3
      - 10.40.1.4
      - 10.40.1.5
      # Old node IPs (during migration)
      - 10.30.4.1
      - 10.30.4.2
      - 10.30.4.3
      - 10.30.4.4
      - 10.30.4.5
      # Load balancers / VIPs
      - 10.30.4.0
      - 10.40.1.0
      # DNS names
      - kubernetes
      - kubernetes.default
      - kubernetes.default.svc
      - kubernetes.default.svc.cluster.local
  - hostname: michigan
    controlPlane: true
    ipAddress: 10.40.1.3
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:76:03
        addresses:
          - 10.30.4.3/11
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 1500
        dhcp: false
      - deviceSelector:
          hardwareAddr: bc:24:11:be:77:03
        addresses:
          - 10.40.1.3/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1
            metric: 100
        vip:
          ip: 10.40.1.0
    certSANs:
      # Node IPs (new network)
      - 10.40.1.1
      - 10.40.1.2
      - 10.40.1.3
      - 10.40.1.4
      - 10.40.1.5
      # Old node IPs (during migration)
      - 10.30.4.1
      - 10.30.4.2
      - 10.30.4.3
      - 10.30.4.4
      - 10.30.4.5
      # Load balancers / VIPs
      - 10.30.4.0
      - 10.40.1.0
      # DNS names
      - kubernetes
      - kubernetes.default
      - kubernetes.default.svc
      - kubernetes.default.svc.cluster.local
  - hostname: erie
    controlPlane: false
    ipAddress: 10.40.1.4
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:76:04
        addresses:
          - 10.30.4.4/11
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 1500
        dhcp: false
      - deviceSelector:
          hardwareAddr: bc:24:11:be:77:04
        addresses:
          - 10.40.1.4/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1
            metric: 100
    certSANs:
      # Node IPs (new network)
      - 10.40.1.1
      - 10.40.1.2
      - 10.40.1.3
      - 10.40.1.4
      - 10.40.1.5
      # Old node IPs (during migration)
      - 10.30.4.1
      - 10.30.4.2
      - 10.30.4.3
      - 10.30.4.4
      - 10.30.4.5
      # Load balancers / VIPs
      - 10.30.4.0
      - 10.40.1.0
      # DNS names
      - kubernetes
      - kubernetes.default
      - kubernetes.default.svc
      - kubernetes.default.svc.cluster.local
  - hostname: ontario
    controlPlane: false
    ipAddress: 10.40.1.5
    installDisk: /dev/sda
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: bc:24:11:be:76:05
        addresses:
          - 10.30.4.5/11
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.0.1
        mtu: 1500
        dhcp: false
      - deviceSelector:
          hardwareAddr: bc:24:11:be:77:05
        addresses:
          - 10.40.1.5/16
        routes:
          - network: 0.0.0.0/0
            gateway: 10.40.0.1
            metric: 100
    certSANs:
      # Node IPs (new network)
      - 10.40.1.1
      - 10.40.1.2
      - 10.40.1.3
      - 10.40.1.4
      - 10.40.1.5
      # Old node IPs (during migration)
      - 10.30.4.1
      - 10.30.4.2
      - 10.30.4.3
      - 10.30.4.4
      - 10.30.4.5
      # Load balancers / VIPs
      - 10.30.4.0
      - 10.40.1.0
      # DNS names
      - kubernetes
      - kubernetes.default
      - kubernetes.default.svc
      - kubernetes.default.svc.cluster.local
controlPlane:
  nameservers:
    - 10.0.0.1
  machineFiles:
    - content: |-
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
          device_ownership_from_security_context = true
      permissions: 0
      path: /etc/cri/conf.d/20-customization.part
      op: create
  disableSearchDomain: true
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/qemu-guest-agent
  patches:
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/openebs/local
              type: bind
              source: /var/openebs/local
              options:
                - rbind
                - rshared
                - rw
    - |-
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: "true"
    - |-
      machine:
        sysctls:
          fs.inotify.max_queued_events: "65536"
          fs.inotify.max_user_instances: "8192"
          fs.inotify.max_user_watches: "524288"
          net.core.rmem_max: "2500000"
          net.core.wmem_max: "2500000"
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedRoles:
                - os:admin
            allowedKubernetesNamespaces:
                - actions-runner-system
                - system-upgrade
          kubePrism:
            enabled: true
            port: 7445
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
worker:
  nameservers:
    - 10.0.0.1
  machineFiles:
    - content: |-
        [plugins."io.containerd.cri.v1.images"]
          discard_unpacked_layers = false
        [plugins."io.containerd.cri.v1.runtime"]
          cdi_spec_dirs = ["/var/cdi/static", "/var/cdi/dynamic"]
          device_ownership_from_security_context = true
      permissions: 0
      path: /etc/cri/conf.d/20-customization.part
      op: create
  disableSearchDomain: true
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/i915
          - siderolabs/qemu-guest-agent
  patches:
    - |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/openebs/local
              type: bind
              source: /var/openebs/local
              options:
                - rbind
                - rshared
                - rw
    - |-
      machine:
        kubelet:
          extraArgs:
            rotate-server-certificates: "true"
    - |-
      machine:
        sysctls:
          fs.inotify.max_queued_events: "65536"
          fs.inotify.max_user_instances: "8192"
          fs.inotify.max_user_watches: "524288"
          net.core.rmem_max: "2500000"
          net.core.wmem_max: "2500000"
    - |-
      machine:
        features:
          kubePrism:
            enabled: true
            port: 7445
          hostDNS:
            enabled: true
            resolveMemberNames: true
            forwardKubeDNSToHost: false
