---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "10.30.4.0/16"

  POSTGRES: "10.30.4.11"
  VECTOR: "10.30.4.13"

  CRUNCHY_POSTGRES: "10.30.4.15"

  # MARIADB
  MARIADB_SVC: "10.30.4.16"
  MARIADB_PRIMARY: "10.30.4.17"
  MARIADB_SECONDARY: "10.30.4.18"
  MARIADB_MAXSCALE: "10.30.4.19"
  MARIADB_MAXSCALE_GUI: "10.30.4.20"
