---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"

  SUPERIOR: "10.40.1.1"
  HURON: "10.40.1.2"
  MICHIGAN: "10.40.1.3"
  ERIE: "10.40.1.4"
  ONTARIO: "10.40.1.5"

  CLUSTER_CIDR: "10.69.0.0/16"

  INTERNAL: "10.40.0.10"
  K8S_GATEWAY: "10.40.0.20"
  EXTERNAL: "10.40.0.30"

  NODE_CIDR_START: "10.40.0.10"
  NODE_CIDR_END: "10.40.0.245"

  JELLYFIN: "10.40.0.100"

  CRUNCHY_POSTGRES: "10.40.0.110"

  # MARIADB
  MAXSCALE: "10.40.0.120"
  MAXSCALE_GUI: "10.40.0.121"

  # VECTOR
  VECTOR: "10.40.0.130"
