---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  CLUSTER_CIDR: "10.69.0.0/16"
  NODE_CIDR: "10.30.4.0/16"

  VECTOR: "10.30.4.13"

  CRUNCHY_POSTGRES: "10.30.4.15"

  # MARIADB
  MAXSCALE: "10.30.4.16"
  MAXSCALE_GUI: "10.30.4.17"
