---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: kromgo
  namespace: observability
  annotations:
    external-dns.alpha.kubernetes.io/target: "${SECRET_CLOUDFLARE_TUNNEL_ID}.cfargotunnel.com"
spec:
  parentRefs:
    - name: external
      namespace: network
      sectionName: https
  hostnames:
    - "kromgo.ewatkins.dev"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /-/ready
      backendRefs:
        - name: kromgo
          port: 8888
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: kromgo
          port: 80
