---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: ClientTrafficPolicy
metadata:
  name: internal-client-policy
  namespace: network
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: internal
  http1:
    enableTrailers: false
  connection:
    bufferLimit: "104857600" # 100MB
  timeout:
    http:
      idleTimeout: 120s
  tls:
    minVersion: "1.2"
  headers:
    xForwardedClientCert:
      mode: AppendForward
