---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./envoyproxy-internal.yaml
  - ./envoyproxy-external.yaml
  - ./gatewayclass-internal.yaml
  - ./gatewayclass-external.yaml
  - ./gateway-internal.yaml
  - ./gateway-external.yaml
  - ./httproute-redirect.yaml
  - ./clienttrafficpolicy-internal.yaml
  - ./clienttrafficpolicy-external.yaml
