apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app envoy-gateway-operator
  namespace: flux-system
spec:
  targetNamespace: envoy-gateway-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: network-certificates
    - name: cilium
  path: ./kubernetes/apps/network/envoy-gateway/operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: talos-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app envoy-gateway-resources
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: envoy-gateway-operator
    - name: network-certificates
  path: ./kubernetes/apps/network/envoy-gateway/gateway
  prune: true
  sourceRef:
    kind: GitRepository
    name: talos-cluster
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app envoy-gateway-monitoring
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: envoy-gateway-operator
    - name: kube-prometheus-stack
  path: ./kubernetes/apps/network/envoy-gateway/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: talos-cluster
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
