---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./certificates/ks.yaml
  - ./cloudflare-tunnel/ks.yaml
  - ./cloudflare-dns/ks.yaml
  - ./envoy-gateway/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./unifi-dns/ks.yaml
